### PR TITLE
Replacing GitHub with omnibuilds

### PR DESCRIPTION
**Pull request by Jake-Pimental**
Terms of service ready to use MVP. Links taken out and makes sense to user

### CODE REVIEW

**Comment by mlinksva** [comment]
Hi, it looks like you might be working on adapting some of the policies here for another company -- OmniBuilds? That's awesome! We'd [love to hear](https://github.com/github/site-policy/blob/master/CONTRIBUTING.md#help-wanted) about how it goes.

But we can't incorporate changes specific to another company into the *GitHub* policies, so closing this particular pull request.

**Comment by Jake-Pimental** [comment]
Sorry my mistake. New github user here

**Comment by mlinksva** [comment]
No problem @Jake-Pimental. Glad you're learning and finding the material here useful. I really meant it above that we'd love to hear how it goes, it wasn't just an excuse to say something nice before closing your pull request. :smile:

**Comment by nsqe** [comment]
Yep, I'll echo @mlinksva — as one of the people who wrote these terms, I'm always excited to see someone else adopting them. We'd love to hear how they work out for you!

Also, welcome to GitHub!

**Comment by Jake-Pimental** [comment]
Thanks for being so kind on this. Its nice to hear encouraging feedback. We are taking a github approach to helping engineers build and track hardware project files.

**Pull request closed without merging**
