### PR TITLE
Update required declarations in Trademark Policy

### PR DESCRIPTION
**Pull request by bluemazzoo**
Adding required declarations to the Trademark Policy, similar to the requirements for a DMCA notice. Some formatting changes show up in the diff, but there are no deletions in this PR, only additions of the declarations mentioned above.

### CODE REVIEW

**Comment by bluemazzoo** [comment]
This pull request will remain open for feedback for the next two weeks, until August 13. At that time, the final version of the changes will be updated in our policy.

**Review by Kixwag-2vappy-hiMxam — COMMENTED** [review]
Githut

**Comment by d066** [comment]
apply all actions

**Review by Hecim1984 — COMMENTED** [review]
🎁

**Review by Bmg00 — APPROVED** [review]
Policies/github-trademark-policy.md
[]()

**Comment by Lameone8614** [comment]
fed4970ef9572d1cad0bc21b68bc27b241d7d1d7

**Review by Lameone8614 — APPROVED** [review]
Goat

**Review by Frankbrids43 — CHANGES_REQUESTED** [review]
I'm not sure who this is related too

**Review by Things-todo — APPROVED** [review]

**Review by DrHeadhunter — COMMENTED** [review]
Ich

**Pull request merged**
